### ISSUE TITLE
What about a Mojo?

### ISSUE THREAD

**Issue by benz0li** [b-data/python-docker-stack#3]
https://www.modular.com/max/mojo

FYI @dkapitan

**Comment by benz0li** [comment]
I will look into this as soon as the [MAX Engine](https://www.modular.com/max/engine) supports Python 3.12.  
ℹ️ Currently, *only* [ Python 3.8 - 3.11](https://docs.modular.com/engine/get-started#requirements) is supported.

Cross reference:

* https://github.com/modularml/max/issues/149

**Comment by benz0li** [comment]
Would be implemented as a separate *docker stack*.

* *Regular* images: Based on `glcr.b-data.ch/python/ver`
* *GPU accelerated* images: Based on `glcr.b-data.ch/cuda/python/ver`

**Comment by dkapitan** [comment]
Very nice! One of the other things I am working on is a Rusty Python stack, see https://github.com/dkapitan/rusty-python-devcontainer

Modifications are in fact very easy, I have just changed some VS Code extensions and Rust-based Python libraries in `requirements.txt`

Still need to change `pip` with `uv`, that really speeds up dependency resolution.

**Comment by benz0li** [comment]
The MAX Engine does not support NVIDIA GPUs yet: https://docs.modular.com/engine/faq#what-hardware-is-currently-supported-by-max-engine

There might be a simple Mojo docker stack at first, as it seems to support Python 3.12 already.

A 'MAX Engine'-based image will be added as soon as the MAX Engine supports Python 3.12 and NVIDIA GPUs.

**Comment by benz0li** [comment]
The *regular* JupyterLab Mojo docker stack is available now: https://github.com/b-data/jupyterlab-mojo-docker-stack  
ℹ️ Based on `glcr.b-data.ch/python/ver:3.12.x`

👉 The *regular* Mojo docker stack as well as Mojo-based [Data Science Dev Containers](https://github.com/b-data/data-science-devcontainers) will follow shortly.

*GPU accelerated* 'MAX Engine'-based JupyterLab images will be added as soon as the MAX Engine supports Python 3.12 and NVIDIA GPUs.  
ℹ️ Supposedly this summer: https://twitter.com/Modular/status/1785131461345157140

**Comment by benz0li** [comment]
> 👉 The *regular* Mojo docker stack as well as Mojo-based [Data Science Dev Containers](https://github.com/b-data/data-science-devcontainers) will follow shortly.

* _Regular_ Mojo docker stack: https://github.com/b-data/mojo-docker-stack/commit/f4dea881ef1deb5301355c178edb47b935f54449
* Mojo-based Data Science Dev Containers: https://github.com/b-data/data-science-devcontainers/commit/4d094c60de250240b4b188fab81959d808054aec
